# This is a basic workflow to help you get started with Actions
name: Profile Readme Development Stats

# Controls when the action will run.
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]
  
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WKAKTIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
