# This is a basic workflow to help you get started with Actions
name: Profile Readme Development Stats

# Controls when the action will run.
on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_LOC_CHART: 'False'
          SHOW_EDITORS: 'False'
          SHOW_TIMEZONE: 'False'
